### ISSUE TITLE
Inconsistencies between my reproduced results and those reported in the paper

### ISSUE THREAD

**Issue by haiahaiah** [JH-lee95/TxtSeg_MTL#6]
Hi, thanks for your work. I have reproduced the experiments, but the reproduced Pk and WD is higher than those reported in the paper. For example, when just training with STP task with negative samples, Pk and WD of [sentence-transformers/all-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L12-v2) on wiki_section_en_disease test set are 18.42 and 20.91. 

Besides, in my opinion, It is worth noting that there exists a bug when computing metric. Specifically, the 298th row code `k = get_k(refs_bcnt)` in [train.py](https://github.com/JH-lee95/TxtSeg_MTL/blob/7e5f5c68730011be450a7ead1830d1452fa56d89/sentence_ver/codes/train.py) get wrong average segment size in reference. Therefore I compute the metric by just calling `segeval.pk` without assigning window_size, which use default window_size computed by [segeval](https://github.com/cfournie/segmentation.evaluation/blob/c4140b48112aac697aa7f05effe8026648ebc501/segeval/window/__init__.py#L22) itself. Finally, the new Pk and WD are 28.92 and 35.21. So I hope that you can check the experiments results.

In addition, to evaluate the ability of the model to truly hit the segmentation point, I compute segmentation positive F1 metric by only calculating the F1 value of the ground truth segmentation point. The positive F1 of [sentence-transformers/all-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L12-v2) on wiki_section_en_disease test set is 53.47. So I also wanna know your paper's F1 metric. As for how to compute positive F1, take a sample with 8 sentences for example, hypothesis sequence is [0, 1, 0, 0, 1, 0, 0, 1] and reference sequence is [0, 1, 1, 0, 1, 0, 1, 0] where 1 means the sentence is end sentence of topic. Then positive F1 of this sample is 57.14. 

Thanks a lot!

**Comment by Ighina** [comment]
Hello,

I confirm that I can't replicate the results as well. Is there any news on this?

Thank you!

**Comment by JH-lee95** [comment]
@haiahaiah could you tell me what bug with get_k did you encounter?

**Comment by Ighina** [comment]
Hi, 
if I can answer for @haiahaiah (and correct me if I'm wrong) the problem is that you use the get_k function directly after using the get_boundary_count function and because you are at that point counting not on a binary sequence such as [0,0,0,1,0,1] but on a sequence such as [4,2] the get_k function behaves in a different way from the one we would want, returning a count that is lower the correct one. Another smaller point is that you subtract the variable reference_count (i.e. the topic initial sentences) from the total number of sentences, which is not how segeval computes the standard window size (in segeval case, the count of sentences include also the reference_count). This is not exactly the way in which you described the k calculation in your paper (from your paper it does look like the calculation should be the same used by segeval) also this might contributes to lower the window_size.
Apparently this has quite strong implications for the final results. You can see also in the github code for Transformer over Transformer (https://github.com/kelvinlo-uni/Transformer-squared/blob/main/transformer_squared_pairwise_only.py) that they themselves have set an arbitrary window size of 10, therefore obtaining results that do not compare equally with the rest of the literature. If you run their code with the standard segeval window size, the results for wiki_disease are much higher. 
Sorry for the long post and I hope this helps!

**Comment by JH-lee95** [comment]
@Ighina Thank you for your kind feedback. Now I can capture an issue with get_k. when we wrote this paper i didn't know that segeval automatically set window size and that's why we calculated "k" with some related functions ourselves.

i'm reviewing the code and modifying some wrong working lines.
Also  i will post new pk, windiff and other metrics with the default segeval setting.

thank you again!

**Comment by JH-lee95** [comment]
@Ighina Thank you for your kind feedback. Now I can capture the issue with get_k. when we wrote this paper i didn't know that segeval automatically set window size and that's why we calculated "k" with some related functions ourselves.

i'm reviewing the code and modifying some wrong working lines.
Also i will post new pk, windiff and other metrics with the default segeval setting.

thank you again!

**Comment by JH-lee95** [comment]
@Ighina @haiahaiah , thank you for your kind feedbacks. Now I can capture the issue with get_k. 

Also I'm reviewing my codes and modifying some wrong working codes. while doing it,  I have found that preprocees.py made wrong sentences in negative sampling.  

when I wrote the paper, I made the negative-sampled trainset with some codes which were fragmented in several parts in jupyter notebooks.  

preprocess.py is for collecting those fragmented codes and doing all the process at once. but while rearranging the codes, some unexpected sentences are sampled.  I think this might be the main reason of discrepancy of experiment results between mine and yours.

i will update the new codes and experiment results as soon as possible. 
thank you!
